### ISSUE TITLE
Any chance the script can be updated to work with the public OAuth1? 

### ISSUE THREAD

**Issue by rafaelcarreno** [bmihaila/twitter-rss-scraper-google-apps-script#5]
Any chance the script can be updated to work with the public OAuth1? Google shut down OAuthConfig ( http://googleappsdeveloper.blogspot.com/2015/03/changes-to-oauth-in-apps-script.html ) on July 6th 2015

**Comment by bmihaila** [comment]
Hi, now back from vacation and again connected to the internet.

Regarding your request. The script does not use OAuth at all as it does not login to Twitter. It just requests and parses the public twitter page for a given user. Hence it still works even if OAuthConfig is deprecated.

The authentication that is currently needed at the first run is requested by Google to allow the script to access the web. There seems no way to not have this dialog on the first run/deployment. At least I am not aware of any. 
However, I updated the Readme as it is not necessary to test run the script to invoke the authorization dialog. A deployment is enough for that.
